names:
  0: oneway
  1: highwayentrance
  2: stop
  3: roundabout
  4: parking
  5: crosswalk
  6: noentry
  7: highwayexit
  8: prio
  9: trafficlight
  10: block
  11: girl
  12: car
num_epochs: 13
test: /home/slsecret/TrafficObjectDetection/bfmc_data/generated/testsets/TestSetAll
train: /home/slsecret/TrafficObjectDetection/bfmc_data/generated/datasets_0415
val: /home/slsecret/TrafficObjectDetection/bfmc_data/generated/testsets/TestSetAll
